FORMAT: 1A
HOST: http://api2.freshrealm.co

# FreshRealm REST API 2.0 Documentation

This document describes the calls needed to interact with FreshRealm’s Merchant API.

# Output Format and Structure
JSON will be returned in all responses from this API, with the following structure.

    {
        "code": 200,
        "timestamp": 1367975121,
        "data": {
            “id”: 5,
            ...,
            ...,
            ...
        }
    }


`Code` is one of the following standard HTTP status codes:

1.  `200` OK
2.  `400` Bad Request
3.  `401` Access Denied
4.  `403` Token key is not valid
5.  `404` Resource Not Found
6.  `500` Internal Server Error
7.  `501` Not Implemented

`Timestamp` is a UNIX timestamp that indicates when the server started processing the request.

`Data` contains attributes of a single resource or array of resources.

# Service Endpoints
An endpoint is the URL of the server that handles your request.  The API endpoint for all requests in this document is http://api2.freshrealm.co/

# Example
In the case where you want to retrieve recent order information, you would use the GET HTTP method to the following URL:

`http://api2.freshrealm.co/orders?key=myaccesstoken`

A `key` is a required attribute for each call. See the authentication diagram at the bottom of this document for more information.

# Requesting Specific Fields
For performance reasons, FreshRealm recommends retrieving the minimum number of fields. In addition, not all fields are retrieved by default, so additional fields may be requested (details of the attributes of the resources are described in the Resource Description section).  To retrieve fewer (or more) fields, use the `fields` attribute in the GET request.

`http://api2.freshrealm.co/orders?fields=["totalPrice"]`

To obtain multiple fields, separate the fields by commas:

`http://api2.freshrealm.co/products/1918?fields=["id","costs","prices”]`

Some calls retrieve nested arrays.  When this is the case you must use the key of the array to retrieve a subset of the fields.  For example to retrieve customer information for order 678 (e.g. email, phone...) you could use this call:

`http://api2.freshrealm.co/orders/678?fields=["customer"]`

# Limit and Offset
Retrieving a large list of resources in one request will degrade performance. Use `limit` and `offset` GET attributes to divide your request into multiple queries. The default value for `limit` is 100.  The default ordering is most recent records first. For example, if we want to get the next 50 orders starting from, and including, position 150 (150th most recent order), use the following call:

`http://api2.freshrealm.co/orders?offset=150&limit=50`

# Filter
Some fields can be used for filtering a list of resources. Filter is a JSON encoded GET attribute that can be defined by a key value pair or as a JSON object with an operator.

### Allowed Operators
`in`, `not in`, `like`, `=`, `<`, `>`, `<=`, `>=`, `!=`

#### Ex: Find customer by email
`http://api2.freshrealm.co/customers?filter={"email":"mycustomer@freshrealm.co"}`

#### Ex: List all orders with a total price greater than $50
`http://api2.freshrealm.co/orders?filter=[{"field":"total","operator":">","value":"50"}]`

### Timestamp Filter
This filter allows retrieval of records created or modified after this time. Every request returns a timestamp, which can be used for this filter. It can be used for database synchronization of products between FreshRealm and your application. The following call would return all orders modified or created after `1367975121`.

`http://api2.freshrealm.co/orders?timestamp=1367975121`

# Contributing
This API documentation lives on Github. If you see an error or a typo, please submit a pull request at [https://github.com/trooprr/freshrealm-api](https://github.com/trooprr/freshrealm-api). We're always happy to have contributions.

# Group Authentication
FreshRealm’s REST API currently uses a proprietary authentication system. Each client gets its own API access key, which must be a part of every request sent to the FreshRealm API.  You must obtain this key by using our authentication call and supplying your secret, which we will provide to you.  At the end of this document a brief diagram is provided to explain our initial authentication system.

##Get Authentication Token [/authenticate]
### POST
+ Request (application/json)
Your FreshRealm secret must be obtained by contacting FreshRealm.

    + Body

            {
                "secret": "myFreshRealmSecret"
            }

+ Response 200 (application/json)

        {
            "code": 200,
            "timestamp": 1465982944,
            "data": {
                "token": "myNewToken"
            }
        }


# Group Products

A **product** is an active item available for you to purchase.

The following table describes which attributes are provided by default, and which can be used as a filter.


| Field                 | Default   | Filter    | Description |
|-----------------------|-----------|-----------|-------------|
| `id`                    | X         | X         | FreshRealm item id |
| `itemName`              | X         |           | Name of the product |
| `customName`            | X         |           | Customize name of the product |
| `sku`                   | X         | X         | Retailer defined item SKU |
| `gtin`                  |           | X         | Global gtin identification number |
| `published`             | X         | X         | A published flag (boolean) |
| `description`           |           | X         | Product description |
| `size`                  | X         | X         | An array containing `height`, `width`, `length`, `containerId`, `containerName`, and `estimatedVesselLoad`. |
| `weight`                | X         | X         |  Weight |
| `weightUnit`            | X         | X         | Unit of weight used e.g. lb, oz, etc. |
| `freshRealmCost`        | X         | X         | FreshRealm Cost |
| `categories`            |           |           | List of categories |
| `updateTime`            |           |           | Time of last update |
| `imageURL`              |           |           | Default image url in the full resolution |
| `nutritionInfo`         | X         |           | Nutritional information for a product. Included by default if individual product is requested but not when list of products is requested |
| `isAvailable`           |           |           | Whether or not it is currently available for purchase |
| `ingredients`           |           |           | Ingredients of the product |
| `allergens`             |           |           | Product allergens |


## List Products [/products?key={token}]
Return all of the products. See the `Products` resource table for more information.

### GET

+ Parameters
    + token (required, string)

+ Response 200 (application/json)

        {
           "code":200,
           "timestamp":1403221161,
           "data":[
              {
                 "id":"1391",
                 "itemName":"Turkey, Egg White & Sundried Tomato Breakfast",
                 "customName":null,
                 "sku":"",
                 "gtin":"10826766900005",
                 "published":"0",
                 "description":null,
                 "size":{
                    "height":"2.26",
                    "width":"3.71",
                    "length":"7.61",
                    "containerId":"1",
                    "containerName":"Medium Container",
                    "estimatedVesselLoad":"5"
                 },
                 "weight":"7.500",
                 "weightUnit":"oz",
                 "freshRealmCost":null,
                 "updateTime":1402509020,
                 "categories":[

                 ],
                 "imageUrl":null,
                 "nutritionInfo":{
                    "Calories":{
                       "amount":"285.36",
                       "unit":"KCal",
                       "weightGrams":null,
                       "percentDaily":15
                    },
                    "Fat Calories":{
                       "amount":"35.86",
                       "unit":"KCal",
                       "weightGrams":null,
                       "percentDaily":8
                    },
                    "Fat":{
                       "amount":"3.98",
                       "unit":"g",
                       "weightGrams":"3.98",
                       "percentDaily":7
                    },
                    "Saturated Fat":{
                       "amount":"1.49",
                       "unit":"g",
                       "weightGrams":"1.49",
                       "percentDaily":8
                    },
                    "Polyunsaturated Fat":{
                       "amount":null,
                       "unit":"g",
                       "weightGrams":null,
                       "percentDaily":0
                    },
                    "Monounsaturated Fat":{
                       "amount":null,
                       "unit":"g",
                       "weightGrams":null,
                       "percentDaily":0
                    },
                    "Trans Fat":{
                       "amount":"0",
                       "unit":"g",
                       "weightGrams":"0",
                       "percentDaily":0
                    },
                    "Cholesterol":{
                       "amount":"14.72",
                       "unit":"mg",
                       "weightGrams":0.01472,
                       "percentDaily":5
                    },
                    "Carbohydrates":{
                       "amount":"48.07",
                       "unit":"g",
                       "weightGrams":"48.07",
                       "percentDaily":17
                    },
                    "Fiber":{
                       "amount":"4.12",
                       "unit":"g",
                       "weightGrams":"4.12",
                       "percentDaily":17
                    },
                    "Sugar":{
                       "amount":"14",
                       "unit":"g",
                       "weightGrams":"14",
                       "percentDaily":16
                    },
                    "Protein":{
                       "amount":"15.84",
                       "unit":"g",
                       "weightGrams":"15.84",
                       "percentDaily":32
                    },
                    "Vitamin A":{
                       "amount":null,
                       "unit":"mcg",
                       "weightGrams":null,
                       "percentDaily":0
                    },
                    "Thiamine B1":{
                       "amount":null,
                       "unit":"mcg",
                       "weightGrams":null,
                       "percentDaily":0
                    },
                    "Vitamin B6":{
                       "amount":null,
                       "unit":"mcg",
                       "weightGrams":null,
                       "percentDaily":0
                    },
                    "Folate B9":{
                       "amount":null,
                       "unit":"mcg",
                       "weightGrams":null,
                       "percentDaily":0
                    },
                    "Vitamin C":{
                       "amount":null,
                       "unit":"mg",
                       "weightGrams":0,
                       "percentDaily":0
                    },
                    "Vitamin E":{
                       "amount":null,
                       "unit":"mg",
                       "weightGrams":0,
                       "percentDaily":0
                    },
                    "Calcium":{
                       "amount":null,
                       "unit":"mg",
                       "weightGrams":0,
                       "percentDaily":0
                    },
                    "Copper":{
                       "amount":null,
                       "unit":"mcg",
                       "weightGrams":null,
                       "percentDaily":0
                    },
                    "Iron":{
                       "amount":null,
                       "unit":"mg",
                       "weightGrams":0,
                       "percentDaily":0
                    },
                    "Phosphorous":{
                       "amount":null,
                       "unit":"mg",
                       "weightGrams":0,
                       "percentDaily":0
                    },
                    "Potassium":{
                       "amount":null,
                       "unit":"mg",
                       "weightGrams":0,
                       "percentDaily":0
                    },
                    "Sodium":{
                       "amount":"549.37",
                       "unit":"mg",
                       "weightGrams":0.54937,
                       "percentDaily":23
                    }
                 },
                 "isAvailable":1,
                 "shippingLocations":[

                 ],
                 "ingredients":[
                    "Grape 1.39\/lb",
                    "Organic Wheat Sandwich Thin 6\/6 ea #3438",
                    "Egg White Patty 3.5\" 160\/1.75 oz #3675766",
                    "Turkey Breast 2\/9-lb 6109724",
                    "Cheese Cream  10\/3 lb #5406467",
                    "Spinach 2.68\/lb",
                    "Sundried Tomato 5.49\/lb"
                 ],
                 "alergens":[

                 ]
              },
              {
                 "id":"1400",
                 "itemName":"Ham & Egg Breakfast Sandwich",
                 "customName":null,
                 "sku":"",
                 "gtin":"10826766900012",
                 "published":"0",
                 "description":null,
                 "size":{
                    "height":"2.26",
                    "width":"3.71",
                    "length":"7.61",
                    "containerId":"1",
                    "containerName":"Medium Container",
                    "estimatedVesselLoad":"5"
                 },
                 "weight":"8.750",
                 "weightUnit":"oz",
                 "freshRealmCost":null,
                 "updateTime":1402509020,
                 "categories":[

                 ],
                 "imageUrl":null,
                 "nutritionInfo":{
                    "Calories":{
                       "amount":"231.67",
                       "unit":"KCal",
                       "weightGrams":null,
                       "percentDaily":12
                    },
                    "Fat Calories":{
                       "amount":"19",
                       "unit":"KCal",
                       "weightGrams":null,
                       "percentDaily":4
                    },
                    "Fat":{
                       "amount":"2.11",
                       "unit":"g",
                       "weightGrams":"2.11",
                       "percentDaily":4
                    },
                    "Saturated Fat":{
                       "amount":"0.15",
                       "unit":"g",
                       "weightGrams":"0.15",
                       "percentDaily":1
                    },
                    "Polyunsaturated Fat":{
                       "amount":null,
                       "unit":"g",
                       "weightGrams":null,
                       "percentDaily":0
                    },
                    "Monounsaturated Fat":{
                       "amount":null,
                       "unit":"g",
                       "weightGrams":null,
                       "percentDaily":0
                    },
                    "Trans Fat":{
                       "amount":null,
                       "unit":"g",
                       "weightGrams":null,
                       "percentDaily":0
                    },
                    "Cholesterol":{
                       "amount":"7.59",
                       "unit":"mg",
                       "weightGrams":0.00759,
                       "percentDaily":3
                    },
                    "Carbohydrates":{
                       "amount":"39.58",
                       "unit":"g",
                       "weightGrams":"39.58",
                       "percentDaily":14
                    },
                    "Fiber":{
                       "amount":"5.44",
                       "unit":"g",
                       "weightGrams":"5.44",
                       "percentDaily":22
                    },
                    "Sugar":{
                       "amount":"14.27",
                       "unit":"g",
                       "weightGrams":"14.27",
                       "percentDaily":16
                    },
                    "Protein":{
                       "amount":"13.24",
                       "unit":"g",
                       "weightGrams":"13.24",
                       "percentDaily":27
                    },
                    "Vitamin A":{
                       "amount":null,
                       "unit":"mcg",
                       "weightGrams":null,
                       "percentDaily":0
                    },
                    "Thiamine B1":{
                       "amount":null,
                       "unit":"mcg",
                       "weightGrams":null,
                       "percentDaily":0
                    },
                    "Vitamin B6":{
                       "amount":null,
                       "unit":"mcg",
                       "weightGrams":null,
                       "percentDaily":0
                    },
                    "Folate B9":{
                       "amount":null,
                       "unit":"mcg",
                       "weightGrams":null,
                       "percentDaily":0
                    },
                    "Vitamin C":{
                       "amount":null,
                       "unit":"mg",
                       "weightGrams":0,
                       "percentDaily":0
                    },
                    "Vitamin E":{
                       "amount":null,
                       "unit":"mg",
                       "weightGrams":0,
                       "percentDaily":0
                    },
                    "Calcium":{
                       "amount":null,
                       "unit":"mg",
                       "weightGrams":0,
                       "percentDaily":0
                    },
                    "Copper":{
                       "amount":null,
                       "unit":"mcg",
                       "weightGrams":null,
                       "percentDaily":0
                    },
                    "Iron":{
                       "amount":null,
                       "unit":"mg",
                       "weightGrams":0,
                       "percentDaily":0
                    },
                    "Phosphorous":{
                       "amount":null,
                       "unit":"mg",
                       "weightGrams":0,
                       "percentDaily":0
                    },
                    "Potassium":{
                       "amount":null,
                       "unit":"mg",
                       "weightGrams":0,
                       "percentDaily":0
                    },
                    "Sodium":{
                       "amount":"497.65",
                       "unit":"mg",
                       "weightGrams":0.49765,
                       "percentDaily":21
                    }
                 },
                 "isAvailable":1,
                 "shippingLocations":[

                 ],
                 "ingredients":[
                    "Orange 5-lb",
                    "Red 88-xf ctn",
                    "Muffin Whole Wheat English 8\/12 oz #77793",
                    "Egg White Patty 3.5\" 160\/1.75 oz #3675766",
                    "Red Bell",
                    "Ham Hormel Low Sodium Presliced 6\/2 lbs #3133"
                 ],
                 "alergens":[

                 ]
              }
           ]
        }

## Get A Product [/products/{id}?key={token}]
Fetch a product by its `id`.

### GET

+ Parameters
    + id (required, number, `1`)
    + token (required, string)

+ Response 200 (application/json)

                {
                    "code": 200,
                    "timestamp": 184653225,
                    "data": {
                        "id":"1391",
                        "itemName":"Turkey, Egg White & Sundried Tomato Breakfast",
                        "customName":null,
                        "sku":"",
                        "gtin":"10826766900005",
                        "published":"0",
                        "description":null,
                        "size":{
                            "height":"2.26",
                            "width":"3.71",
                            "length":"7.61",
                            "containerId":"1",
                            "containerName":"Medium Container",
                            "estimatedVesselLoad":"5"
                        },
                        "weight":"7.500",
                        "weightUnit":"oz",
                        "freshRealmCost":null,
                        "updateTime":1402509020,
                        "categories":[

                        ],
                        "imageUrl":null,
                        "nutritionInfo":{
                            "Calories":{
                                "amount":"285.36",
                                "unit":"KCal",
                                "weightGrams":null,
                                "percentDaily":15
                            },
                            "Fat Calories":{
                                "amount":"35.86",
                                "unit":"KCal",
                                "weightGrams":null,
                                "percentDaily":8
                            },
                            "Fat":{
                                "amount":"3.98",
                                "unit":"g",
                                "weightGrams":"3.98",
                                "percentDaily":7
                            },
                            "Saturated Fat":{
                                "amount":"1.49",
                                "unit":"g",
                                "weightGrams":"1.49",
                                "percentDaily":8
                            },
                            "Polyunsaturated Fat":{
                                "amount":null,
                                "unit":"g",
                                "weightGrams":null,
                                "percentDaily":0
                            },
                            "Monounsaturated Fat":{
                                "amount":null,
                                "unit":"g",
                                "weightGrams":null,
                                "percentDaily":0
                            },
                            "Trans Fat":{
                                "amount":"0",
                                "unit":"g",
                                "weightGrams":"0",
                                "percentDaily":0
                            },
                            "Cholesterol":{
                                "amount":"14.72",
                                "unit":"mg",
                                "weightGrams":0.01472,
                                "percentDaily":5
                            },
                            "Carbohydrates":{
                                "amount":"48.07",
                                "unit":"g",
                                "weightGrams":"48.07",
                                "percentDaily":17
                            },
                            "Fiber":{
                                "amount":"4.12",
                                "unit":"g",
                                "weightGrams":"4.12",
                                "percentDaily":17
                            },
                            "Sugar":{
                                "amount":"14",
                                "unit":"g",
                                "weightGrams":"14",
                                "percentDaily":16
                            },
                            "Protein":{
                                "amount":"15.84",
                                "unit":"g",
                                "weightGrams":"15.84",
                                "percentDaily":32
                            },
                            "Vitamin A":{
                                "amount":null,
                                "unit":"mcg",
                                "weightGrams":null,
                                "percentDaily":0
                            },
                            "Thiamine B1":{
                                "amount":null,
                                "unit":"mcg",
                                "weightGrams":null,
                                "percentDaily":0
                            },
                            "Vitamin B6":{
                                "amount":null,
                                "unit":"mcg",
                                "weightGrams":null,
                                "percentDaily":0
                            },
                            "Folate B9":{
                                "amount":null,
                                "unit":"mcg",
                                "weightGrams":null,
                                "percentDaily":0
                            },
                            "Vitamin C":{
                                "amount":null,
                                "unit":"mg",
                                "weightGrams":0,
                                "percentDaily":0
                            },
                            "Vitamin E":{
                                "amount":null,
                                "unit":"mg",
                                "weightGrams":0,
                                "percentDaily":0
                            },
                            "Calcium":{
                                "amount":null,
                                "unit":"mg",
                                "weightGrams":0,
                                "percentDaily":0
                            },
                            "Copper":{
                                "amount":null,
                                "unit":"mcg",
                                "weightGrams":null,
                                "percentDaily":0
                            },
                            "Iron":{
                                "amount":null,
                                "unit":"mg",
                                "weightGrams":0,
                                "percentDaily":0
                            },
                            "Phosphorous":{
                                "amount":null,
                                "unit":"mg",
                                "weightGrams":0,
                                "percentDaily":0
                            },
                            "Potassium":{
                                "amount":null,
                                "unit":"mg",
                                "weightGrams":0,
                                "percentDaily":0
                            },
                            "Sodium":{
                                "amount":"549.37",
                                "unit":"mg",
                                "weightGrams":0.54937,
                                "percentDaily":23
                            }
                        },
                        "isAvailable":1,
                        "shippingLocations":[

                        ],
                        "ingredients":[
                            "Grape 1.39\/lb",
                            "Organic Wheat Sandwich Thin 6\/6 ea #3438",
                            "Egg White Patty 3.5\" 160\/1.75 oz #3675766",
                            "Turkey Breast 2\/9-lb 6109724",
                            "Cheese Cream  10\/3 lb #5406467",
                            "Spinach 2.68\/lb",
                            "Sundried Tomato 5.49\/lb"
                        ],
                        "alergens":[

                        ]
                    }
                }



## Fetch Specific Fields [/products/{productId}?key={token}&fields={fieldsList}]
These examples show how to limit the returned data to a specific set of fields.

### List of Ingredents [GET]
+ Parameters
    + token (required, string)
    + productId (required, number)
    + fieldsList (optional, array, `["id", "ingedients"]`)


+ Response 200 (application/json)

        {
            "code": "200",
            "timestamp": "1376939257",
            "data": {
                "id": "2203",
                "ingredients": [{
                    "url": "api2.freshrealm.co/items/2201?key=FgDqgXUUP7dh38zb2CSCmcyookXnTgM",
                    "id": "2201",
                    "amount": "0.5",
                    "unit": "ft"
                }]
            }
        }


## Filter Example [/products?key={token}&filter={filter}]
Some fields can be used for filtering a list of resources. `Filter` is a JSON encoded GET attribute that can be defined by a key value pair or as a JSON object with an operator.

### GET
+ Parameters
    + token (required, string)
    + filter (optional, array, `[{"field": "name", "value": "%Egg%", "operator:"like"}]`)


+ Response 200 (application/json)

        {
            "code": 200,
            "timestamp": 1403221501,
            "data": [
                {
                    "id": "1391",
                    "itemName": "Turkey, Egg White & Sundried Tomato Breakfast",
                    "customName": null,
                    "sku": "",
                    "gtin": "10826766900005",
                    "published": "0",
                    "description": null,
                    "size": {
                        "height": "2.26",
                        "width": "3.71",
                        "length": "7.61",
                        "containerId": "1",
                        "containerName": "Medium Container",
                        "estimatedVesselLoad": "5"
                    },
                    "weight": "7.500",
                    "weightUnit": "oz",
                    "freshRealmCost": null,
                    "updateTime": 1402509020,
                    "categories": [],
                    "imageUrl": null,
                    "nutritionInfo": {
                        "Calories": {
                            "amount": "285.36",
                            "unit": "KCal",
                            "weightGrams": null,
                            "percentDaily": 15
                        },
                        "Fat Calories": {
                            "amount": "35.86",
                            "unit": "KCal",
                            "weightGrams": null,
                            "percentDaily": 8
                        },
                        "Fat": {
                            "amount": "3.98",
                            "unit": "g",
                            "weightGrams": "3.98",
                            "percentDaily": 7
                        },
                        "Saturated Fat": {
                            "amount": "1.49",
                            "unit": "g",
                            "weightGrams": "1.49",
                            "percentDaily": 8
                        },
                        "Polyunsaturated Fat": {
                            "amount": null,
                            "unit": "g",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Monounsaturated Fat": {
                            "amount": null,
                            "unit": "g",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Trans Fat": {
                            "amount": "0",
                            "unit": "g",
                            "weightGrams": "0",
                            "percentDaily": 0
                        },
                        "Cholesterol": {
                            "amount": "14.72",
                            "unit": "mg",
                            "weightGrams": 0.01472,
                            "percentDaily": 5
                        },
                        "Carbohydrates": {
                            "amount": "48.07",
                            "unit": "g",
                            "weightGrams": "48.07",
                            "percentDaily": 17
                        },
                        "Fiber": {
                            "amount": "4.12",
                            "unit": "g",
                            "weightGrams": "4.12",
                            "percentDaily": 17
                        },
                        "Sugar": {
                            "amount": "14",
                            "unit": "g",
                            "weightGrams": "14",
                            "percentDaily": 16
                        },
                        "Protein": {
                            "amount": "15.84",
                            "unit": "g",
                            "weightGrams": "15.84",
                            "percentDaily": 32
                        },
                        "Vitamin A": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Thiamine B1": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Vitamin B6": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Folate B9": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Vitamin C": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Vitamin E": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Calcium": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Copper": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Iron": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Phosphorous": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Potassium": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Sodium": {
                            "amount": "549.37",
                            "unit": "mg",
                            "weightGrams": 0.54937,
                            "percentDaily": 23
                        }
                    },
                    "isAvailable": 1,
                    "shippingLocations": [],
                    "ingredients": [
                        "Grape 1.39/lb",
                        "Organic Wheat Sandwich Thin 6/6 ea #3438",
                        "Egg White Patty 3.5\" 160/1.75 oz #3675766",
                        "Turkey Breast 2/9-lb 6109724",
                        "Cheese Cream    10/3 lb #5406467",
                        "Spinach 2.68/lb",
                        "Sundried Tomato 5.49/lb"
                    ],
                    "alergens": []
                },
                {
                    "id": "1400",
                    "itemName": "Ham & Egg Breakfast Sandwich",
                    "customName": null,
                    "sku": "",
                    "gtin": "10826766900012",
                    "published": "0",
                    "description": null,
                    "size": {
                        "height": "2.26",
                        "width": "3.71",
                        "length": "7.61",
                        "containerId": "1",
                        "containerName": "Medium Container",
                        "estimatedVesselLoad": "5"
                    },
                    "weight": "8.750",
                    "weightUnit": "oz",
                    "freshRealmCost": null,
                    "updateTime": 1402509020,
                    "categories": [],
                    "imageUrl": null,
                    "nutritionInfo": {
                        "Calories": {
                            "amount": "231.67",
                            "unit": "KCal",
                            "weightGrams": null,
                            "percentDaily": 12
                        },
                        "Fat Calories": {
                            "amount": "19",
                            "unit": "KCal",
                            "weightGrams": null,
                            "percentDaily": 4
                        },
                        "Fat": {
                            "amount": "2.11",
                            "unit": "g",
                            "weightGrams": "2.11",
                            "percentDaily": 4
                        },
                        "Saturated Fat": {
                            "amount": "0.15",
                            "unit": "g",
                            "weightGrams": "0.15",
                            "percentDaily": 1
                        },
                        "Polyunsaturated Fat": {
                            "amount": null,
                            "unit": "g",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Monounsaturated Fat": {
                            "amount": null,
                            "unit": "g",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Trans Fat": {
                            "amount": null,
                            "unit": "g",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Cholesterol": {
                            "amount": "7.59",
                            "unit": "mg",
                            "weightGrams": 0.00759,
                            "percentDaily": 3
                        },
                        "Carbohydrates": {
                            "amount": "39.58",
                            "unit": "g",
                            "weightGrams": "39.58",
                            "percentDaily": 14
                        },
                        "Fiber": {
                            "amount": "5.44",
                            "unit": "g",
                            "weightGrams": "5.44",
                            "percentDaily": 22
                        },
                        "Sugar": {
                            "amount": "14.27",
                            "unit": "g",
                            "weightGrams": "14.27",
                            "percentDaily": 16
                        },
                        "Protein": {
                            "amount": "13.24",
                            "unit": "g",
                            "weightGrams": "13.24",
                            "percentDaily": 27
                        },
                        "Vitamin A": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Thiamine B1": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Vitamin B6": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Folate B9": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Vitamin C": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Vitamin E": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Calcium": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Copper": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Iron": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Phosphorous": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Potassium": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Sodium": {
                            "amount": "497.65",
                            "unit": "mg",
                            "weightGrams": 0.49765,
                            "percentDaily": 21
                        }
                    },
                    "isAvailable": 1,
                    "shippingLocations": [],
                    "ingredients": [
                        "Orange 5-lb",
                        "Red 88-xf ctn",
                        "Muffin Whole Wheat English 8/12 oz #77793",
                        "Egg White Patty 3.5\" 160/1.75 oz #3675766",
                        "Red Bell",
                        "Ham Hormel Low Sodium Presliced 6/2 lbs #3133"
                    ],
                    "alergens": []
                }
            ]
        }

## Limit and Offset Example [/products?key={token}&limit={limit}&offset={offset}]
Retrieving a large list of resources in one request will degrade performance. Use the `limit` and `offset` GET attributes to divide your request into multiple queries. The default value for limit is 100.

### GET

+ Parameters
    + token (required, string)
    + limit (optional, number, `2`)
    + offset (optional, number, `1`)

+ Response 200 (application/json)

        {
            "code": 200,
            "timestamp": 1403221501,
            "data": [
                {
                    "id": "1391",
                    "itemName": "Turkey, Egg White & Sundried Tomato Breakfast",
                    "customName": null,
                    "sku": "",
                    "gtin": "10826766900005",
                    "published": "0",
                    "description": null,
                    "size": {
                        "height": "2.26",
                        "width": "3.71",
                        "length": "7.61",
                        "containerId": "1",
                        "containerName": "Medium Container",
                        "estimatedVesselLoad": "5"
                    },
                    "weight": "7.500",
                    "weightUnit": "oz",
                    "freshRealmCost": null,
                    "updateTime": 1402509020,
                    "categories": [],
                    "imageUrl": null,
                    "nutritionInfo": {
                        "Calories": {
                            "amount": "285.36",
                            "unit": "KCal",
                            "weightGrams": null,
                            "percentDaily": 15
                        },
                        "Fat Calories": {
                            "amount": "35.86",
                            "unit": "KCal",
                            "weightGrams": null,
                            "percentDaily": 8
                        },
                        "Fat": {
                            "amount": "3.98",
                            "unit": "g",
                            "weightGrams": "3.98",
                            "percentDaily": 7
                        },
                        "Saturated Fat": {
                            "amount": "1.49",
                            "unit": "g",
                            "weightGrams": "1.49",
                            "percentDaily": 8
                        },
                        "Polyunsaturated Fat": {
                            "amount": null,
                            "unit": "g",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Monounsaturated Fat": {
                            "amount": null,
                            "unit": "g",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Trans Fat": {
                            "amount": "0",
                            "unit": "g",
                            "weightGrams": "0",
                            "percentDaily": 0
                        },
                        "Cholesterol": {
                            "amount": "14.72",
                            "unit": "mg",
                            "weightGrams": 0.01472,
                            "percentDaily": 5
                        },
                        "Carbohydrates": {
                            "amount": "48.07",
                            "unit": "g",
                            "weightGrams": "48.07",
                            "percentDaily": 17
                        },
                        "Fiber": {
                            "amount": "4.12",
                            "unit": "g",
                            "weightGrams": "4.12",
                            "percentDaily": 17
                        },
                        "Sugar": {
                            "amount": "14",
                            "unit": "g",
                            "weightGrams": "14",
                            "percentDaily": 16
                        },
                        "Protein": {
                            "amount": "15.84",
                            "unit": "g",
                            "weightGrams": "15.84",
                            "percentDaily": 32
                        },
                        "Vitamin A": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Thiamine B1": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Vitamin B6": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Folate B9": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Vitamin C": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Vitamin E": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Calcium": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Copper": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Iron": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Phosphorous": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Potassium": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Sodium": {
                            "amount": "549.37",
                            "unit": "mg",
                            "weightGrams": 0.54937,
                            "percentDaily": 23
                        }
                    },
                    "isAvailable": 1,
                    "shippingLocations": [],
                    "ingredients": [
                        "Grape 1.39/lb",
                        "Organic Wheat Sandwich Thin 6/6 ea #3438",
                        "Egg White Patty 3.5\" 160/1.75 oz #3675766",
                        "Turkey Breast 2/9-lb 6109724",
                        "Cheese Cream    10/3 lb #5406467",
                        "Spinach 2.68/lb",
                        "Sundried Tomato 5.49/lb"
                    ],
                    "alergens": []
                },
                {
                    "id": "1400",
                    "itemName": "Ham & Egg Breakfast Sandwich",
                    "customName": null,
                    "sku": "",
                    "gtin": "10826766900012",
                    "published": "0",
                    "description": null,
                    "size": {
                        "height": "2.26",
                        "width": "3.71",
                        "length": "7.61",
                        "containerId": "1",
                        "containerName": "Medium Container",
                        "estimatedVesselLoad": "5"
                    },
                    "weight": "8.750",
                    "weightUnit": "oz",
                    "freshRealmCost": null,
                    "updateTime": 1402509020,
                    "categories": [],
                    "imageUrl": null,
                    "nutritionInfo": {
                        "Calories": {
                            "amount": "231.67",
                            "unit": "KCal",
                            "weightGrams": null,
                            "percentDaily": 12
                        },
                        "Fat Calories": {
                            "amount": "19",
                            "unit": "KCal",
                            "weightGrams": null,
                            "percentDaily": 4
                        },
                        "Fat": {
                            "amount": "2.11",
                            "unit": "g",
                            "weightGrams": "2.11",
                            "percentDaily": 4
                        },
                        "Saturated Fat": {
                            "amount": "0.15",
                            "unit": "g",
                            "weightGrams": "0.15",
                            "percentDaily": 1
                        },
                        "Polyunsaturated Fat": {
                            "amount": null,
                            "unit": "g",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Monounsaturated Fat": {
                            "amount": null,
                            "unit": "g",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Trans Fat": {
                            "amount": null,
                            "unit": "g",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Cholesterol": {
                            "amount": "7.59",
                            "unit": "mg",
                            "weightGrams": 0.00759,
                            "percentDaily": 3
                        },
                        "Carbohydrates": {
                            "amount": "39.58",
                            "unit": "g",
                            "weightGrams": "39.58",
                            "percentDaily": 14
                        },
                        "Fiber": {
                            "amount": "5.44",
                            "unit": "g",
                            "weightGrams": "5.44",
                            "percentDaily": 22
                        },
                        "Sugar": {
                            "amount": "14.27",
                            "unit": "g",
                            "weightGrams": "14.27",
                            "percentDaily": 16
                        },
                        "Protein": {
                            "amount": "13.24",
                            "unit": "g",
                            "weightGrams": "13.24",
                            "percentDaily": 27
                        },
                        "Vitamin A": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Thiamine B1": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Vitamin B6": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Folate B9": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Vitamin C": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Vitamin E": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Calcium": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Copper": {
                            "amount": null,
                            "unit": "mcg",
                            "weightGrams": null,
                            "percentDaily": 0
                        },
                        "Iron": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Phosphorous": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Potassium": {
                            "amount": null,
                            "unit": "mg",
                            "weightGrams": 0,
                            "percentDaily": 0
                        },
                        "Sodium": {
                            "amount": "497.65",
                            "unit": "mg",
                            "weightGrams": 0.49765,
                            "percentDaily": 21
                        }
                    },
                    "isAvailable": 1,
                    "shippingLocations": [],
                    "ingredients": [
                        "Orange 5-lb",
                        "Red 88-xf ctn",
                        "Muffin Whole Wheat English 8/12 oz #77793",
                        "Egg White Patty 3.5\" 160/1.75 oz #3675766",
                        "Red Bell",
                        "Ham Hormel Low Sodium Presliced 6/2 lbs #3133"
                    ],
                    "alergens": []
                }
            ]
        }

## Price By Zipcode [/products/{id}?key={token}&zip={zipcode}&fields={fieldsList}]
Get the price of a product for a given zipcode.

### GET
+ Parameters
    + token (required, string)
    + id (required, number)
    + zipcode (required, string, `95660`)
    + fieldsList (optional, array, `["id", "name", "freshRealmCost"]`)

+ Response 200 (application/json)

        {
            "code": "200",
            "timestamp": "1376939257",
            "data": {
                "id": "2189",
                "name": "Item 2",
                "freshRealmCost": "2.34"
            }
        }


# Group Orders

## Place An Order [/orders]
To create an order, you must pass a `customerId`. If the `customerId` is not provided an error will be thrown.

### Attributes
| field          | required | type      | example                               | description |
|-----------------------|:-:|-----------|---------------------------------------|-------------|
| `customerId`            | * | int       | `1`                                   | Customer Id, see `Customers` resource |
| `shippingAddressId`            | * | int       | `1`                                   | Shipping Address Id, see `Addresses` resource |
| `items`            | * | array    | [...] | See below |
| `status`              |   | string    | `authorized` | The current status of the order. May be one of the following: `preliminary, authorized, test` |
| `orderNumber`         |   | string    | `123532` | Optional. The order number within your application. |
| `deliveryDate`          |   | string    | `06-28-2014` | Optional for orders not on the earliest delivery date |
| `codropId`   |   | int    |  | If the order is for Co-Drop, required |
| `totalPrice`   |   | float    |  | The total price of the order |
| `salesTax`   |   | float    |  | The sales tax applied to the order |
| `transactionId`   |   | int    |  | The transaction to which this order is linked. See `Transactions` resource |

#### Items Attributes
| field | required  | type      | example                           | description |
|---------------|:-:|-----------|-----------------------------------|-------------|
| `itemId`        | * | int       | `1`                               | FreshRealm Item ID |
| `quantity`           | * | int       | `1`                               | Quantity |


### Place An Order [POST]

+ Request (application/json)

    + Body

            {
                "status": "authorized",
                "customerId": 7069,
                "shippingAddressId": 7427,
                "items": [{
                    "itemId": "1674",
                    "quantity": 3
                },{
                    "itemId": "1675",
                    "quantity": 4
                }],
                "totalPrice": "20.98",
                "salesTax": "0",
                "deliveryDate": "2014-06-01",
            }

+ Response 200 (application/json)

        {
            "code": 200,
            "timestamp": 1401213818,
            "data": {
                "id": "10489",
                "customerId": "7069",
                "codropId": null,
                "shippingAddressId": "7427",
                "status": "authorized",
                "manufactureDate": "2014-06-02",
                "freshrealmSubtotal": 4.05,
                "shippingAndHandling": 30.79182,
                "cutOffTime": "2014-05-30 17:00",
                "totalCost": 34.84182,
                "totalPrice": "20.98",
                "salesTax": "0",
                "updateTime": 1401213818,
                "createTime": 1401213818,
                "orderNumber": null,
                "deliveryDate": "2014-06-02",
                "items": [
                    {
                        "id": "1674",
                        "quantity": 3
                    },
                    {
                        "id": "1675",
                        "quantity": 4
                    }
                ],
                "pickupDate": null,
                "shipMethod": "FEDEX_GROUND",
                "warnings": [
                    {
                        "type": "modifiedDeliveryDate",
                        "message": "Delivery date was modified"
                    }
                ]
            }
        }

## List Orders [/orders?key={token}&limit={limit}]

Retrieve all the latest orders (default limit is 100 results)

### List Orders [GET]
+ Parameters
    + token (required, string)
    + limit (optional, number, `3`)

+ Response 200 (application/json)

        {
            "code": 200,
            "timestamp": 1401213818,
            "data": [{
                "id": "10489",
                "customerId": "7069",
                "codropId": null,
                "shippingAddressId": "7427",
                "status": "authorized",
                "manufactureDate": "2014-06-02",
                "freshrealmSubtotal": 4.05,
                "shippingAndHandling": 30.79182,
                "cutOffTime": "2014-05-30 17:00",
                "totalCost": 34.84182,
                "totalPrice": "20.98",
                "salesTax": "0",
                "updateTime": 1401213818,
                "createTime": 1401213818,
                "orderNumber": null,
                "deliveryDate": "2014-06-02",
                "items": [
                    {
                        "id": "1674",
                        "quantity": 3
                    },
                    {
                        "id": "1675",
                        "quantity": 4
                    }
                ],
                "pickupDate": null,
                "shipMethod": "FEDEX_GROUND"
            },{
                "id": "10490",
                "customerId": "7069",
                "codropId": null,
                "shippingAddressId": "7427",
                "status": "authorized",
                "manufactureDate": "2014-06-02",
                "freshrealmSubtotal": 4.05,
                "shippingAndHandling": 30.79182,
                "cutOffTime": "2014-05-30 17:00",
                "totalCost": 34.84182,
                "totalPrice": "20.98",
                "salesTax": "0",
                "updateTime": 1401213818,
                "createTime": 1401213818,
                "orderNumber": null,
                "deliveryDate": "2014-06-02",
                "items": [
                    {
                        "id": "1674",
                        "quantity": 3
                    },
                    {
                        "id": "1675",
                        "quantity": 4
                    }
                ],
                "pickupDate": null,
                "shipMethod": "FEDEX_GROUND"
            },{
                "id": "10491",
                "customerId": "7069",
                "codropId": null,
                "shippingAddressId": "7427",
                "status": "authorized",
                "manufactureDate": "2014-06-02",
                "freshrealmSubtotal": 4.05,
                "shippingAndHandling": 30.79182,
                "cutOffTime": "2014-05-30 17:00",
                "totalCost": 34.84182,
                "totalPrice": "20.98",
                "salesTax": "0",
                "updateTime": 1401213818,
                "createTime": 1401213818,
                "orderNumber": null,
                "deliveryDate": "2014-06-02",
                "items": [
                    {
                        "id": "1674",
                        "quantity": 3
                    },
                    {
                        "id": "1675",
                        "quantity": 4
                    }
                ],
                "pickupDate": null,
                "shipMethod": "FEDEX_GROUND"
            }]
        }

## Order Resource [/order/{orderId}?key={token}]
Use this URL to `GET` order information or `PUT` changes to the order.

### Fetch Order [GET]
+ Parameters
    + orderId (required, number, `10490`)
    + token (required, string)

+ Response 200 (application/json)

        {
            "code": 200,
            "timestamp": 1402706999
            "data": {
                "id": "10490",
                "customerId": "7069",
                "codropId": null,
                "shippingAddressId": "7427",
                "status": "authorized",
                "manufactureDate": "2014-06-02",
                "freshrealmSubtotal": 4.05,
                "shippingAndHandling": 30.79182,
                "cutOffTime": "2014-05-30 17:00",
                "totalCost": 34.84182,
                "totalPrice": "20.98",
                "salesTax": "0",
                "updateTime": 1401213818,
                "createTime": 1401213818,
                "orderNumber": null,
                "deliveryDate": "2014-06-02",
                "items": [
                    {
                        "id": "1674",
                        "quantity": 3
                    },
                    {
                        "id": "1675",
                        "quantity": 4
                    }
                ],
                "pickupDate": null,
                "shipMethod": "FEDEX_GROUND"
            }
        }


### Update Order [PUT]

+ Parameters
    + orderId (required, number, `109`)
    + token (required, string)

+ Request (application/json)
This call allows you to modify an order. Once an order has reached the `processed` status, it can no longer be updated. This status change occurs at the `cutOffTime`.

The input `id` must match the `orderId` in the URL.

    + Body

            {
                "id": 109
            }

+ Response 200 (application/json)

        {
            "code": 200,
            "timestamp": 1377020859,
            "data": {
                "id":109,
                "status": "CANCELLED"
            }
        }


# Group Customers

This operation can be used to find a customer and to get all the orders for the customer.

|Field                      |Default        |Filter                 |Description |
|---------------------------|---------------|-----------------------|------------|
|id                         |X              |X                      |FreshRealm customer id |
|firstName                  |X              |X                      |First name of customer |
|lastName                   |X              |X                      |Last name of customer |
|email                      |X              |X                      |Email Address |
|phone                      |X              |X                      |Phone Number |
|addresses                  |X              |X                      |List of the latest shipping addresses |
|customerID                 |X              |X                      |The external customer id (customer id set by customers of FreshRealm) |


## List of orders placed by the customer [/customers/{customerId}?key={token}]

### GET

+ Parameters
    + token (required, string)
    + customerId (required, number)


+ Response 200 (application/json)

        {
            "code": 200,
            "timestamp": 1377020859,
            "data": {
                "id": "228",
                "firstName": "Bob",
                "lastName": "Smith",
                "email": "numberonebob@bob.com",
                "phone": "8051234567",
                "customerId": ""
            }
        }


#Group Addresses

This operation can be used to find addresses and get all the addresses for a customer.

|Field              |Description        |
|-------------------|-------------------|
|`streetAndNumber`    |Example: 476 Main St       |
|`aptSuite`           |Apartment number, unit number or suite. Example: Unit A        |
|`city`               |City name      |
|`state`              |State name - Example: CA or California     |
|`verify`             |Set to `1` to run validation against address database. This extra validation can catch incorrect zipcode or house number. Use this feature to make sure that the package will be delivered to the right address. |

# Group Categories

This operation can be used to find available categories to which products belong.  See the ‘Categories’  resource table for more information.

| Field | Default | Filter | Description |
|-------|---------|--------|-------------|
| `id` | X | X | Category id |
| `parentId` | X | X | Id of a parent category if category is a subcategory of another category |
| `name` | X | X | Category name |
| `published` | X | X | Whether a category is activated or not |
| `imageUrl` |  |  | Returns urls of images that are attached to category (optional |
| `parentUrl` |  |  | Url of a parent category if such category exists |


## List Categories [/categories?key={token}]
### GET
+ Parameters
    + token (required, string)

+ Response 200 (application/json)

            {
                "code": 200,
                "timestamp": 1402706999
                "data":[{
                    "id": "293",
                    "name": "Category 1"
                },{
                    "id": "294",
                    "name": "Category 2"
                },{
                    "id": "295",
                    "name": "Category 3"
                }]
            }

##Retrieve An Individual Category [/categories/{categoryId}?key={token}]
### GET
+ Parameters
    + token (required, string)
    + categoryId (required, number)

+ Response 200 (application/json)

            {
               "id": "293",
               "parentId": "",
               "name": "Category 1",
               "published": "1"
            }


#Group Transactions
Use Case Scenario:
This operation can be used to retrieve a list of all the transactions. Get transactions will give you the ids for those requested transaction to allow you to then get orders for them.

[TBD]


#Group Co-Drops
Use these methods to obtain information about Co-Drop, request individual Co-Drop information, get list of customers belonging to a Co-Drop, or create a Co-Drop.

Codrops allow multiple customers to have food delivered to one location. Co-Drops can be public or private, and can be open to all or by invite only. The FreshRealm API allows retrieving information about all Co-Drops or individual Co-Drop, as well as creation of a new Co-Drop.


| Field | Default | Filter | Description |
|-------|---------|--------|-------------|
| `id` | X | X | FreshRealm Co-Drop id |
| `name` | X | X | Co-Drop name |
| `address` | X |  | Address of a Co-Drop |
| `facilitator` |  |  | Information about Co-Drop's facilitator |
| `notes` | X | X | Notes |
| `active` | X | X | Flag whether Co-Drop is active |
| `timestamp` |  | X | Latest timestamp when the Co-Drop was updated |
| `inviteRequired` |  | X | Whether invite is required |
| `chargePerOrder` | X | X | Charge per order |


## Co-Drops Collection [/codrops?key={token}]
### List Co-Drops [GET]

+ Parameters
    + token (required, string)

+ Response 200 (application/json)

        {
            "code": 200,
            "timestamp": 1402706999
            "data": [{
                "id": "75",
                "name": "TestDrop1",
                "address": "110 North 13th Street, Las Vegas, NV, 89101",
                "facilitator": {
                    "firstName": "Facilitator",
                    "lastNameUser": "",
                    "email": "test_facilitator1@freshrealm.co",
                    "phone": "9999999010"
                }
            }]
        }

### Create Co-Drop [POST]

+ Parameters
    + token (required, string)

+ Request

        {
            "name": "API_TestCodrop",
            "inviteRequired": "",
            "active": "",
            "notes": "Test codrop created through API",
            "addressFields": {
                "streetAndNumber": "500 Poli St",
                "aptSuite": "A",
                "city": "Ventura",
                "state": "CA",
                "zipcode": "93001"
            }
        }


+ Response 200 (application/json)

        {
            "id": "79"
            "name": "API_TestCodrop"
            "notes": "Test codrop created through API"
            "active": "",
            "timestamp": "2013-08-20 20:10:05"
            "inviteRequired": "",
            "public": "",
            "chargePerOrder": "0.00"
        }

## Get Information About Individual Co-Drop [/codrops/{codropId}?key={token}]
### GET

+ Parameters
    + token (required, string)
    + codropId (required, number)

+ Response 200 (application/json)

            {
                "code": 200,
                "timestamp": 1402706999
                "data": {
                    "id": "75",
                    "name": "TestDrop1",
                    "notes": "public drop",
                    "active": "1",
                    "timestamp": "2013-08-20 19:38:23"
                    "inviteRequired":
                    "public": "1",
                    "chargePerOrder": "0.00"
                }
            }

## Get List of Customers Belonging To a Particular Co-Drop [/codrops/{codropId}/customrs?key={token}]
### GET

+ Parameters
    + codropId (required, number)
    + token (required, string)

+ Response 200 (application/json)

            {
                "code": 200,
                "timestamp": 1402706999
                "data":[{
                      "id": "233",
                      "firstName": "Bob",
                      "lastName": "Smith",
                      "email": "numberonebob@bob.com",
                      "phone": "8051234567",
                      "address": "200 E Main St, Ventura, CA, 93001"
                },{
                      "id": "234",
                      "firstName": "David",
                      "lastName": "Sobotka",
                      "email": "david@sobotka.com",
                      "phone": "8131234567",
                      "address": "3501 Interstate 275 Frontage Rd E, Tampa, FL, 33607"
                }]
            }


#Group Shipping

###Get Shipping Details
This operation is used at the checkout page to get the shipping cost and earliest delivery date based on the items and address that the food is being delivered to without placing the actual order.

| Field | Default | Filter | Description |
|-------|---------|--------|-------------|
| id | X | X | Shipment id |
| shipMethod | X | X | Indicates what postal carrier was used to ship the shipment. Possible values are ‘fedex’, ‘usps’, ‘ups’ etc |
| updateTime |  | X | Latest timestamp when the shipment was updated |
| shippingAddress | X |  | Address resource where shipment was delivered (see Address resource above for more info |
| shipToName | X |  | Name of shipment recipient |
| shippingLines | X |  |  Array of shipping lines. Every shipping line contains the following information: `productNumber`, `vesselNumber`, `customerName`, `slotNumber`, `vesselNotchNumber`, `unitPrice`, `labelInfo`, `vesselSize` |

##Download Shipments Information [/shipments?key={token}&timestamp={timestamp}]

### Shipment Information [GET]
+ Parameters
    + token (required, string)
    + timestamp (optional, number)

+ Response 200 (application/json)

        {
            "code": 200,
            "timestamp": 1402706999
            "data": {
                "streetAndNumber": "200 E Main St",
                "aptSuite": "",
                "city": "Ventura",
                "state": "CA",
                "zipcode": "93001",
                "country": "US",
                "shipToName": "Bob Smith",
                "shippingLines":[{
                    "productNumber": "coolant",
                    "vesselNumber": "0",
                    "slotNumber": "0",
                    "vesselNotchNumber": "0",
                    "unitPrice": "N/A",
                    "labelInfo": "N/A",
                    "vesselSize": "Large"
                }]
            }
        }

## Update Shipping Information [/shipments/{shipmentId}?key={token}]

### PUT

+ Parameters
    + token (required, string)
    + shipmentId (required, number, `45`)

+ Request

        {
            "id": "45",
            "shipDate": "2013-07-05",
            "actualFreightCost": "23.33",
            "vessels": [{
                "id": "45",
                "vesselNumber": "1234567",
                "trackingNumber": "7423542523374",
                "trackingNumberBack": "7423542523374",
                "actualWeight": "5.34",
                "drawers": [{
                    "slotNumber": "2",
                    "drawerNumber": "4893rhjf487rt7484jviuref874"
                },{
                    "slotNumber": "3",
                    "drawerNumber": "474fhf375t76fh374984564j45gj"
                }]
            }]
        }

+ Response 200 (application/json)

        {
            "code": "200",
            "timestamp": "1377032713",
            "data": {
                "id": "45"
            }
        }

##Get Shipping Details [/getshippingdetails?key={token}]
###Get Shipping Details [GET]

+ Parameters
    + token (required, string)

+ Response 200 (application/json)

        {
            "code": 200,
            "timestamp": 1402706999
            "data": {
                "customer": {
                    "firstName": "Joe",
                    "lastName": "Smith",
                    "email": "joesgvggggmith@yahoo.com",
                    "phone": "8051234567",
                    "customerNumber": "555RTT",
                    "addressFields": {
                        "streetAndNumber": "476 E Main Street",
                        "aptSuite": "200",
                        "city": "Ventura",
                        "state": "CA",
                        "zipcode": "93001"
                    },
                    "shoppingCart": [{
                        "sku": "XFEG8228",
                        "itemId": "2189",
                        "qty": "2"
                    },{
                        "sku": "FGSXBSNW",
                        "itemId": "2192",
                        "qty": "7"
                    }]
                }
            }
        }

## Update shipping information for a codrop [/shipments/{shipmentId}?key={token}]

### Update shipping information for a codrop [PUT]

+ Parameters
    + token (required, string)
    + shipmentId (required, number)

+ Response 200 (application/json)

        {
            "code": 200,
            "timestamp": 1402706999
            "data": {
                "id": "46",
                "shipDate": "2013-07-05",
                "actualFreightCost": "23.33",
                "vessels": [{
                    "vesselNumber": "1234567",
                    "trackingNumber": "9923542523374",
                    "trackingNumberBack": "9923542523374",
                    "actualWeight": "225.34",
                    "drawers": [{
                        "slotNumber": "2",
                        "drawerNumber": "4893rhjf487rt7484jviuref874"
                    },{
                        "slotNumber": "3",
                        "drawerNumber": "474fhf375t76fh374984564j45gj"
                    }]
                }]
            }
        }

#Group Other API Calls

## Get Drawers [/drawers?key={token}]

###All drawers [GET]

+ Parameters
    + token (required, string)

+ Response 200 (application/json)

        {
            "code": 200,
            "timestamp": 1402706999
            "data":[{
                "id": "76",
                "barcode": "4893rhjf487rt7484jviuref874",
                "status": "clean",
                "updateTime": "1377025877"
            },{
                "id": "77",
                "barcode": "474fhf375t76fh374984564j45gj",
                "status": "clean",
                "updateTime": "1377025878"
            }]
        }

##Get Vessels [/vessels?key={token}]

###Get Vessels[GET]

+ Parameters
    + token (required, string)

+ Response 200 (application/json)

        {
            "code": "200",
            "timestamp": "1377026573",
            "data": [{
                "id": "29",
                "vesselTypeId": "2",
                "vesselNumber": "1234567",
                "status": "ready",
                "updateTime": "1377026572"
            },{
                "id": "30",
                "vesselTypeId": "3",
                "vesselNumber": "7654321",
                "status":  "in use",
                "updateTime": "1377026572"
            }]
        }

##Get Vessel Load [/vesselload?key={token}]

### Get Vessel Load [POST]

+ Parameters
    + token (required, string)

+ Request (application/json)

        [{
            "itemId": 2252,
            "qty": 2
        },{
            "itemId": 2249,
            "qty": 2
        }]

+ Response 200 (application/json)

        {
            "code": "200",
            "timestamp": "1377029658",
            "data": {
                "size": "Large",
                "load": "27",
                "itemsInside": "4",
                "freeSpace": "11",
                "shippingWeight": "29.3"
            }
        }

##Create Picknpack Product Receipt [/pnpproductreceipts?key={token}]
###Create Picknpack Product Receipt [POST]
Note: receipt date is optional. If no receipt date is provided, receipt date will be pre-filled with the date when API request is initiated.

+ Parameters
    + token (required, string)


+ Request (application/json)

        {
            "itemId" : "2248",
            "receiptDate": "2013-06-01 04:00:00",
            "quantity": "8",
            "location": "A1",
            "picknpackId": "213"
        }

+ Response 200 (application/json)

        {
            "code": "200",
            "timestamp": "13031633",
            "data": {
                "id": "2",
                "itemId": "2248",
                "receiptDate": "2013-06-01 04:00:00",
                "quantity": "8",
                "location": "A1",
                "picknpackId": "213",
                "createTime": "2013-08-20 20:47:13",
                "updateTime": "2013-08-20 20:47:13"
            }
        }